apiVersion: apps/v1
kind: Deployment
metadata:
  name: obnpctl
  labels:
    component: client
spec:
  selector:
    matchLabels:
      app: obnpctl
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
      - name: cli
        image: postgres:14.2
        volumeMounts:
        - mountPath: /home/store
          name: store
      volumes:
      - name: store
        secret:
          # this is very fragile and depends on the secret PostgresCluster creates
          # try to follow https://github.com/kubernetes-sigs/kustomize/tree/b0d7721049d557063e324c7c2c1ef45bb73e4bdc/examples/transformerconfigs/crd for a better solution
          secretName: hippo-postgres-pguser-hippo-postgres
