apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  comm-type: postgres
resources:
- ../base
- postgresclusters.postgres-operator.crunchydata.com_hippo.yaml
- subscriptions.operators.coreos.com_crunchy-postgres-operator.yaml
nameSuffix: -postgres
patchesStrategicMerge:
- deploy_load-postgres-secret.yaml
