name: release
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x ]
        include:
          - check-latest: true
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: ${{ matrix.check-latest }}
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Setup go-task/task
        uses: lukeshay/setup-task@v1
      - name: Test
        run: pwd; ls; task test-with-coverage
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@a36c7ef8f23b2952fa6e39663f52107dfc8ad69d
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  release:
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
      - name: install cosign
        uses: sigstore/cosign-installer@v3.0.1
        with:
          cosign-release: 'v1.6.0'
      - uses: anchore/sbom-action/download-syft@v0.13.3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: 'v1.6.3'
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
