name: Verify Shell Code
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
