name: Verify Shell Code
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
