name: Verify Shell Code
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
