name: Verify Shell Code
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
