name: Verify Shell Code
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
