name: Verify URL's
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Setup golang
      uses: actions/setup-go@v3
     #uses: actions/setup-go@v2.2.0
      with:
        check-latest: true
    - name: Install vl
      run: go install github.com/npxbr/verify-links/cmd/vl@latest
    # TODO: add caching for this install 
    - name: Check URLs
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
