name: Verify URL's
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: Setup golang
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
     #uses: actions/setup-go@v2.2.0
      with:
        go-version-file: go.mod
    - name: Install vl
      run: |
        go install github.com/ellisonleao/vl/cmd/vl@main
        echo ${HOME}/go/bin >> $GITHUB_PATH
    # TODO: add caching for this install 
    - name: Check URLs
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
