name: Verify URL's
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Setup golang
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
     #uses: actions/setup-go@v2.2.0
      with:
        go-version-file: go.mod
    - name: Install vl
      run: |
        go install github.com/ellisonleao/vl/cmd/vl@main
        echo ${HOME}/go/bin >> $GITHUB_PATH
    # TODO: add caching for this install 
    - name: Check URLs
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
