name: Verify URL's
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Setup golang
      uses: actions/setup-go@v4
     #uses: actions/setup-go@v2.2.0
      with:
        go-version-file: go.mod
    - name: Install vl
      run: |
        go install github.com/ellisonleao/vl/cmd/vl@main
        echo ${HOME}/go/bin >> $GITHUB_PATH
    # TODO: add caching for this install 
    - name: Check URLs
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
