apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: obnpctl
  name: obnpctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obnpctl
  template:
    metadata:
      labels:
        app: obnpctl
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - bash
        image: ghcr.io/georgettica/obnpctl:latest
        workingDir: /home/store
        name: cli
        stdin: true
        stdinOnce: true
        tty: true
        resources:
          limits:
            cpu: "200m"
            memory: "13Mi"
      imagePullSecrets:
      - name: georgettica-ghcr-registry
